openapi: 3.0.1
info:
  title: Store Information
  description: Get Store Information endpoint, manage store profile settings.
  version: ''
servers:
  - url: https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2
security:
  - X-Auth-Token: []
tags:
  - name: Store Information
  - name: Time Zone
paths:
  /store:
    get:
      tags:
        - Store Information
      summary: Get Store Information
      description: Returns metadata about a store.
      parameters:
        - name: Accept
          in: header
          required: true
          schema:
            type: string
            default: application/json
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            default: application/json
      responses:
        '200':
          description: ''
          content:
            Time:
              schema:
                $ref: '#/components/schemas/StoreInformation'
            application/json:
              example:
                id: abc123
                domain: my-awesome.store
                secure_url: https://my-awesome.stor
                control_panel_base_url: https://store-{store_hash}.mybigcommerce.com
                status: live
                name: BigCommerce
                first_name: Jane
                last_name: Doe
                address: BigCommerce
                country: United States
                country_code: US
                phone: ''
                admin_email: jane.does@example.com
                order_email: info@janedoes.mybigcommerce.com
                favicon_url: >-
                  https://cdn8.bigcommerce.com/r-8816ba2f48b0bcf4bec0c1a954c00e0fc36b/img/bc_favicon.ico
                timezone:
                  name: America/Chicago
                  raw_offset: -21600
                  dst_offset: -18000
                  dst_correction: true
                  date_format:
                    display: M jS Y
                    export: M jS Y
                    extended_display: M jS Y @ g:i A
                language: en
                currency: USD
                currency_symbol: $
                decimal_separator: .
                thousands_separator: ','
                decimal_places: 2
                currency_symbol_location: left
                weight_units: Ounces
                dimension_units: Inches
                dimension_decimal_places: 2
                dimension_decimal_token: .
                dimension_thousands_token: ','
                plan_name: Standard
                plan_level: Standard
                industry: ''
                logo:
                  url: >-
                    https://cdn8.bigcommerce.com/s-{store_hash}/product_images/screen_shot_2018-05-15_at_12.22.26_pm__05547_1529512135.png
                is_price_entered_with_tax: false
                active_comparison_modules: []
                features:
                  stencil_enabled: true
                  sitewidehttps_enabled: false
                  facebook_catalog_id: ''
                  checkout_type: optimized
            Response Schema:
              example:
                id: nostrud pariatur incididunt
                domain: consequat ut amet
                secure_URL: consectetur ullamco ut Excepteur
                name: id qui cupidatat anim tempor
                first_name: ut dolore elit
                last_name: cupidatat minim
                address: tempor
                country: ex cupidatat
                phone: aliquip dolore pariatur
                admin_email: dolor commodo elit do
                order_email: ea qui
                timezone:
                  name: culpa quis sint eiusmod ut
                  raw_offset: -25825722
                  dst_offset: -97926378
                  dst_correction: false
                  date_format:
                    display: cupidatat
                    export: est
                    extended_display: cillum qui esse aliquip culpa
                language: nulla commodo incididunt dolor ipsum
                currency: amet in
                currency_symbol: cupidatat deserunt est pariatur
                decimal_separator: in consectetur nisi officia
                thousands_separator: ea irure occaecat qui
                decimal_places: {}
                currency_symbol_location: est cupidatat
                weight_units: minim adipisicing do
                dimension_units: deserunt
                dimension_decimal_places: 50514826
                dimension_decimal_token: deserunt est aliqua Duis
                'dimension_thousands_token:': sint voluptate esse tempor
                plan_name: Ut
                plan_level: pariatur ullamco veniam ad
                industry: pariatur culpa est
                logo:
                  url: aliquip in aliqua consectetur ullamco
                is_price_entered_with_tax: false
                features:
                  stencil_enabled: true
                  sitewidehttps_enabled: anim occaecat exercitation conse
                  facebook_catalog_id: aliquip sed adipisicing quis
                  checkout_type: qui mollit id aliqua ut
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /time:
    get:
      tags:
        - Time Zone
      summary: Get System Timestamp
      description: >-
        Returns the system timestamp at the time of the request. The time
        resource is useful for validating API authentication details and testing
        client connections.
      parameters:
        - name: Accept
          in: header
          required: true
          schema:
            type: string
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/timeStamp_Full'
              example:
                time: 1529512970
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
components:
  schemas:
    StoreInformation:
      title: Store Information
      type: object
      properties:
        id:
          type: string
          description: Unique store identifier.
          example: store_hash
        domain:
          type: string
          description: Primary domain name.
          example: your-store-url.com
        secure_URL:
          type: string
          description: Store’s current HTTPS URL.
          example: https://your-store-url.com
        control_panel_base_url:
          type: string
          description: The secure hostname of the control panel.
          example: '"https://store-abc123.mybigcommerce.com"'
        name:
          type: string
          description: Store's name.
          example: BigCommerce
        first_name:
          type: string
          description: >-
            Primary contact’s first name (as defined during the store sign-up
            process).
          example: Jane
        last_name:
          type: string
          description: >-
            Primary contact’s last name (as defined during the store sign-up
            process).
          example: Doe
        address:
          type: string
          description: Display address.
          example: BigCommerce
        country:
          type: string
          description: >-
            Country where the store is located (as defined during the store
            sign-up process).
          example: United States
        phone:
          type: string
          description: Display phone number.
        admin_email:
          type: string
          description: Email address of the store administrator/owner.
          example: janedoes@example.com
        order_email:
          type: string
          description: Email address for orders and fulfillment.
          example: orders@emai
        timezone:
          $ref: '#/components/schemas/Timezone'
        language:
          type: string
          description: Default language code.
          example: en
        currency:
          type: string
          description: Default currency code
          example: USD
        currency_symbol:
          type: string
          description: Default symbol for values in the currency.
          example: $
        decimal_separator:
          type: string
          description: Default decimal separator for values in the currency.
          example: .
        thousands_separator:
          type: string
          description: Default thousands separator for values in the currency.
          example: ','
        decimal_places:
          type: integer
          description: Default decimal places for values in the currency.
          example: 2
        currency_symbol_location:
          type: string
          description: Default position of the currency symbol (left or right).
          example: left
        weight_units:
          type: string
          description: Default weight units (metric or imperial).
          example: Ounces
        dimension_units:
          type: string
          description: Default dimension units (metric or imperial).
          example: Inches
        dimension_decimal_places:
          type: integer
          description: The number of decimal places.
          example: 2
        dimension_decimal_token:
          type: string
          description: The symbol that separates the whole numbers from the decimal points.
          example: .
        'dimension_thousands_token:':
          type: string
          description: The symbol used to denote thousands.
        plan_name:
          type: string
          description: Name of the BigCommerce plan to which this store is subscribed.
          example: Standard
        plan_level:
          type: string
          description: Level of the BigCommerce plan to which this store is subscribed.
          example: Standard
        industry:
          type: string
          description: >-
            Industry, or vertical category, in which the business operates. (As
            selected from drop-down list during the store sign-up process.)
          example: Technology
        logo:
          type: object
          properties:
            url:
              type: string
              example: >-
                https://cdn8.bigcommerce.com/s-{store_hash}/product_images/screen_shot_2018-05-15_at_12.22.26_pm__05547_1529512135.png"
        is_price_entered_with_tax:
          type: boolean
          description: >-
            A Boolean value that indicates whether or not prices are entered
            with tax.
          example: false
        active_comparison_modules:
          type: array
          description: ''
          items:
            type: object
        features:
          type: object
          properties:
            stencil_enabled:
              type: boolean
              description: Indicates whether a store is using a Stencil theme.
              example: true
            sitewidehttps_enabled:
              type: string
              description: Indicates if there is sitewide https.
              example: 'false'
            facebook_catalog_id:
              type: string
              description: >-
                Id of the facebook catalog. If there is none, it returns an
                empty string. 
            checkout_type:
              type: string
              description: >-
                What type of checkout is enabled on the store. Possible values
                returned are optimized, single (one page), single_customizable
                (one page for developers), klarna.
              example: optimized
          description: |-
            + `stencil_enabled`: `true` (boolean)
                + `sitewidehttps_enabled`: `false` (boolean)
                + `facebook_catalog_id` (string)
    Timezone:
      title: Time Zone
      type: object
      properties:
        name:
          type: string
          description: >-
            a string identifying the time zone, in the format:
            <Continent-name>/<City-name>.
          example: America/Chicago
        raw_offset:
          type: integer
          description: >-
            a negative or positive number, identifying the offset from UTC/GMT,
            in seconds, during winter/standard time.
          example: -21600
        dst_offset:
          type: integer
          description: >-
            "-/+" offset from UTC/GMT, in seconds, during summer/daylight saving
            time.
          example: -18000
        dst_correction:
          type: boolean
          description: >-
            a boolean indicating whether this time zone observes daylight saving
            time.
          example: true
        date_format:
          $ref: '#/components/schemas/DateFormat'
    DateFormat:
      title: Date Format
      type: object
      properties:
        display:
          type: string
          description: 'string that defines dates’ display format, in the pattern: M jS Y'
          example: M jS Y
        export:
          type: string
          description: >-
            string that defines the CSV export format for orders, customers, and
            products, in the pattern: M jS Y
          example: M jS Y
        extended_display:
          type: string
          description: >-
            string that defines dates’ extended-display format, in the pattern:
            M jS Y @ g:i A.
          example: M jS Y @ g:i A
    timeStamp_Full:
      title: timeStamp_Full
      type: object
      properties:
        time:
          minimum: 0
          type: integer
          format: int64
      description: Store Time in Unix format.
  securitySchemes:
    X-Auth-Token:
      type: apiKey
      description: >-
        ### OAuth Scopes

        |  **UI Name** | **Permission** | **Parameter** |

        | --- | --- | --- |

        |  Information & Settings | modify | `store_v2_information` |

        |  Information & Settings | read-only | `store_v2_information_read_only`
        |


        ### Headers


        |Header|Parameter|Description|

        |-|-|-|

        |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
        installing an app in a BigCommerce control panel.|


        ### Example


        ```http

        GET /stores/{$$.env.store_hash}/v3/catalog/summary

        host: api.bigcommerce.com

        Content-Type: application/json

        X-Auth-Token: {access_token}

        ```


        * For more information on Authenticating BigCommerce APIs, see:
        [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). 
      name: X-Auth-Token
      in: header
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
