openapi: 3.0.0
info:
  version: ""
  title: Tax Classes
  description: Manage tax calculations applied to sales. Tax classes are used to apply
    different tax rates for specific types of products and orders. This API is
    read only. Classes must be set using the [Control
    Panel](https://forum.bigcommerce.com/s/article/Taxes-Video#).
paths:
  "/stores/{store_hash}/v2/tax_classes":
    get:
      description: |-
        Returns a list of all *Tax Classes* in a store.

        Default sorting is by tax-class id, from lowest to highest.
      summary: Get All Tax Classes
      tags:
        - Taxes
      parameters:
        - name: Accept
          in: header
          required: true
          description: ""
          schema:
            type: string
            default: application/json
        - name: Content-Type
          in: header
          required: true
          description: ""
          schema:
            type: string
            default: application/json
        - name: page
          in: query
          required: false
          description: Optional filter param. Number of pages.
          schema:
            type: number
            maximum: 50
            exclusiveMinimum: false
            exclusiveMaximum: false
        - name: limit
          in: query
          required: false
          description: Optional filter param. Number of items per page
          schema:
            type: number
            maximum: 250
            exclusiveMinimum: false
            exclusiveMaximum: false
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/taxClass_Full"
              examples:
                response:
                  value:
                    - id: 1
                      name: Non-Taxable Products
                      created_at: 1973-01-20T21:34:57.903Z
                      updated_at: 1990-12-30T00:29:23.515Z
                    - id: 2
                      name: Shipping
                      created_at: 1973-01-20T21:34:57.903Z
                      updated_at: 1990-12-30T00:29:23.515Z
                    - id: 3
                      name: Gift Wrapping
                      created_at: 1973-01-20T21:34:57.903Z
                      updated_at: 1990-12-30T00:29:23.515Z
            Response Schema:
              examples:
                response:
                  value:
                    - id: proident irure consequat anim
                      name: sed non commodo et tempor
                      created_at: 1973-01-20T21:34:57.903Z
                      updated_at: 1990-12-30T00:29:23.515Z
                    - id: consequat voluptate
                      name: sunt ex
                      created_at: 1973-01-20T21:34:57.903Z
                      updated_at: 1990-12-30T00:29:23.515Z
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      operationId: getAllTaxClasses
    parameters:
      - name: store_hash
        in: path
        required: true
        schema:
          type: string
  "/stores/{store_hash}/v2/tax_classes/{id}":
    get:
      description: Returns a single *Tax Class*.
      summary: Get a Tax Class
      tags:
        - Taxes
      parameters:
        - name: id
          in: path
          required: true
          description: Id of the tax class.
          schema:
            type: integer
        - name: Accept
          in: header
          required: true
          description: ""
          schema:
            type: string
        - name: Content-Type
          in: header
          required: true
          description: ""
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/taxClass_Full"
              examples:
                response:
                  value:
                    id: 1
                    name: Shipping
                    created_at: 1973-01-20T21:34:57.903Z
                    updated_at: 1990-12-30T00:29:23.515Z
            Response Schema:
              examples:
                response:
                  value:
                    id: ut pariatur eiusmod non
                    name: dolore nulla Duis Ut ea
                    created_at: 1973-01-20T21:34:57.903Z
                    updated_at: 1990-12-30T00:29:23.515Z
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      operationId: getATaxClass
    parameters:
      - name: store_hash
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
tags:
  - name: Taxes
security:
  - X-Auth-Token: []
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
servers:
  - url: https://api.bigcommerce.com
components:
  securitySchemes:
    X-Auth-Token:
      type: apiKey
      name: X-Auth-Token
      in: header
      description: >-
        ### OAuth Scopes

        |  **UI Name** | **Permission** | **Parameter** |

        | --- | --- | --- |

        |  Information & Settings | modify | `store_v2_information` |

        |  Information & Settings | read-only | `store_v2_information_read_only` |


        ### Headers


        |Header|Parameter|Description|

        |-|-|-|

        |`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|


        ### Example


        ```http

        GET /stores/{store_hash}/v3/catalog/summary

        host: api.bigcommerce.com

        Content-Type: application/json

        X-Auth-Token: {access_token}

        ```


        * For more information on Authenticating BigCommerce APIs, see: [Authentication](/api-docs/getting-started/authentication). 
  schemas:
    taxClass_Full:
      title: taxClass_Full
      example:
        id: 1
        name: Shipping
        created_at: 1973-01-20T21:34:57.903Z
        updated_at: 1990-12-30T00:29:23.515Z
      type: object
      properties:
        id:
          description: The unique numerical ID of the tax class. A read-only value which is
            automatically assigned and increments sequentially.
          example: 1
          type: string
        name:
          description: The name of the tax class.
          example: Shipping
          type: string
        created_at:
          description: Date and time of the tax class' creation. Read-Only.
          example: 2018-05-07T20:14:17+00:00
          format: date-time
          type: string
        updated_at:
          description: Date and time when the tax class was last updated. Read-Only.
          example: 2018-05-07T20:14:17+00:00
          format: date-time
          type: string
      x-internal: false